- pom.xml
groupId and artifactId in pom.xml changed
> <groupId> and <artifactId> in pom.xml changed

- src/test/java/runner/IrynaHryhorivTest.java
testH2Text_WhenSearchingCityCountry() added
> IrynaHryhoriv

- src/test/java/YuliyaShershenTest.java
testH2TagTextWhenSearchingCityCountry() added
> yuliyaShershen1

- src/test/java/NatalliaOwlTest.java
> NatalliaOwl1

- src/test/java/ElNov686Test.java
testH2TagTextWhenSearchingCityCountry() added
> ElNov686-1

- src/test/java/IreneSnitkoTest.java
Added testGuideMenuOpeningGuidePage()
> IreneSnitko

- src/test/java/LiudmilaPlucciTest.java
> LiudmilaPlucci2

- src/test/java/Elena_STest.java
testOpenWeatherPageGuidMaximixe() throws added
> Elena_S_PR

- src/test/java/Gaukhar2022Test.java
> gaukhar-2022

- src/test/java/Dasha1991Test.java
> Dasha1991First

- src/test/java/Natalia1903Test.java
> Natalia19031

- src/test/java/ElNov686Test.java
> RFElNov686testTemperatureImperialFahrenheitVerify

- src/test/java/IvanRamin7Test.java
Removed wrong notation "driver.quit"
> My first testing branch

- src/test/java/OlgaAlmazTest.java
testH2Tagtest_WhenSearchingCityCountry added
> OlgaAlmaz1

- src/test/java/OlgaAlmazTest.java
> Olga alma test

- src/test/java/AndreyGolovTest.java
1. Deleted some unused imports and methods (miximize window etc) and redundant gaps in code;
2. testCookiesWarningPanelAndTwoButtonsOnItDisplayed_WhenMainPageStarts added;
> AndreyGolov3

- src/test/java/Dasha1991Test.java
> testCheckUseCookies() addeDasha1991

- src/test/java/ViraDmytrenkoTest.java
New test "testTitleTextAndURLText()" added
> ViraDmytrenko

- src/test/java/ElNov686Test.java
testVerifyCookiesTextAndTwoButtons() added
> ElNov686Test changed 

- src/test/java/ViktoriyaEDTest.java
test_APICheck30Buttons() added
> ViktoriyaED

- src/test/java/MariaKuzhTest.java
> MariaKuzh1

- src/test/java/VeraFesTest.java
FahrenheitUnits_IfChooseF test added
> verafestest2

- src/test/java/Btv35Test.java
> testH2TagText_WhenSearchingCityCountry() added

- src/test/java/ElNov686Test.java
testMenuAPI_Verify30orangeButtons() added
> ElNov686Test changed

- src/test/java/VladimirMikhnevichTest.java
testH2TagTextWhenSearchingCityCountry() added
> VladimirMikhnevich1

- src/test/java/EkaterinaChernyshovaTest.java
- src/test/java/VladimirMikhnevichTest.java
> testATMainNavBarMenuGuideIsClickableHappyStrawberryAT_EkaterinaLizina

- src/test/java/TchernomorTest.java
testH2Tag_WhenSearchingCityCountry_Tchernomor() test added
> stole smbs test testH2Tag_WhenSearchingCityCountry

- src/test/java/Nikolaymarkov3Test.java
test2agext_henearchingityountry() added
> ATnikolaymarkov31

- src/test/java/TatyanaBelikovaTest.java
testH2TagText_WhenSearchingCityCountry
> Tatyana-Belikova

- src/test/java/TatianaR2022Test.java
testH2TagText_WhenSearchingCityCountry()
> TatianaR20221

- src/test/java/AndreyGolovTest.java
> ATAndreyGolov4

- src/test/java/KsutitovaTest.java
RF - https://trello.com/c/UAxj08JI/197-rfstartweather-h2-add-url-and-metods-for-testh2textopenweathermapinguidelink-ksutitova
> [RF][Start][Weather] [h2] add URL and metods for tests <ksutitova>

- src/test/java/ViktoriiaHukTest.java
testWenPageApiHas30OrangeButten refactored
[RF] - https://trello.com/c/qc9ZFvmp/221-rfmainnavbarapi-viktoriiahuktest-testwenpageapihas30orangebuttenviktoriiahuk
> [RF][Main][NavBar][API] ViktoriiaHukTest/testWenPageApiHas30OrangeButten<ViktoriiaHuk>

- src/test/java/VeraFesTest.java
[RF][Main][NavBar][Logo] test_LogoExistsClickableRedirects2Start was refactored
[RF][Main][NavBar][Logo] Verify the website's logo is exists, clickable and it redirects a User to the Start page <verafes>
https://trello.com/c/aPj7Y7TB/284-rfmainnavbarlogo-verify-the-websites-logo-is-exists-clickable-and-it-redirects-a-user-to-the-start-page-verafes
2 tests deleted:
[RF][Weather][GuideMenu] testTitle_WhenGoingToGuideMenu() deleted <verafes>
https://trello.com/c/xXbzERF5/282-rfweatherguidemenu-testtitlewhengoingtoguidemenu-deleted-verafes
[RF][Start][SearchCity] testH2TagText_WhenSearchingCityCountry() deleted <verafes>
https://trello.com/c/NPJmTcEj/274-rfstartsearchcity-testh2tagtextwhensearchingcitycountry-deleted-verafes
> [RF][Main][NavBar][Logo] test_LogoExistsClickableRedirects2Start was refactored <verafes>

- src/test/java/OMalanovaTest.java
testNoticeText_WhenCityNameFromRandomSymbols added
[TC] - https://trello.com/c/4ENHC1nq/451-tcstartweather-searchblock-testnoticetextwhencitynamefromrandomsymbols-omalanova
[AT] - https://trello.com/c/ccFa5GQ0/455-atstartweather-searchblock-testnoticetextwhencitynamefromrandomsymbols-omalanova
> [AT][Start][Weather] [SearchBlock] testNoticeText_WhenCityNameFromRandomSymbols <omalanova>

- src/test/java/ViraDmytrenkoTest.java
gnored testTitleTextAndURLText() deleted
[RF] - https://trello.com/c/tU8nVW0U/667-rfmainnavbarmenuguide-ignored-testtitletextandurltext-deleted-vira-dmytrenko
> [RF][Main][NavBar][Menu][Guide] ignored testTitleTextAndURLText() deleted <vira-dmytrenko>

- src/test/java/VeraFesTest.java
testLogo_WhenClickRedirects2Start() refactored
[RF] https://trello.com/c/J5IE6T2g/854-rfmainnavbarlogo-testlogowhenclickredirects2start-verafes
> [RF][Main][NavBar][Logo] testLogo_WhenClickRedirects2Start() <verafes>

- src/test/java/base/BaseTest.java
getAttribute() method added to BaseTest
The method allows getting any attribute of the tested element
[US] https://trello.com/c/fO9UArBg/869-usstructurebasepage-add-getattribute-method-to-basetest-verafes
[AT] https://trello.com/c/cVZsVpu8/870-atstructurebasepage-add-getattribute-method-to-basetest-verafes
> [AT][Structure][BasePage] Add getAttribute() method to BaseTest <Verafes>

- src/test/java/base/BaseTest.java
duplicated GetAttributeMethod removed
[RF] https://trello.com/c/9JewJlPg/875-rfstructurebasepage-gettestbyattribute-method-to-basetest-verafes
> [RF][Structure][BasePage] getAttribute() method removed from BaseTest <Verafes>

- src/test/java/VeraFesTest.java
testLogoLink() added
[TC] https://trello.com/c/xB4vK7Kg/878-tcmainnavbarlogo-verify-logo-exist-and-has-a-linkverafes
[AT] https://trello.com/c/KqQCK36T/879-atmainnavbarlogo-verify-logo-exist-and-has-a-linkverafes
> [AT][Main][NavBar][Logo] testLogoLink() added <verafes>

- src/test/java/AikaTest.java
- src/test/java/AnnaAbgTest.java
- src/test/java/AsyniaginaTest.java
- src/test/java/BugorDmitriyTest.java
- src/test/java/DimaZadrutsiyTest.java
- src/test/java/DmswlpkTest.java
- src/test/java/ElNov686Test.java
- src/test/java/ElviraKh1Test.java
- src/test/java/IrynaHryhorivTest.java
- src/test/java/IrynaKolyadaTest.java
- src/test/java/LarisaBratukhinaTest.java
- src/test/java/Lenochkanik80Test.java
- src/test/java/Maksim2404Test.java
- src/test/java/MariJernTest.java
- src/test/java/MaxIaskoTest.java
- src/test/java/NataliaRamanenkaTest.java
- src/test/java/NataliiaOliverTest.java
- src/test/java/RadasIvanTest.java
- src/test/java/TellenqaTest.java
- src/test/java/VeraFesTest.java
- src/test/java/ViktorLytovchenkoTest.java
- src/test/java/ViktoriyaEDTest.java
- src/test/java/WeraStremedlowskaTest.java
- src/test/java/YanDadaelovTest.java
- src/test/java/base/BaseTest.java
> ATvladimirmikhnevich

- src/test/java/TimberhutTest.java
- src/test/java/base/BaseTest.java
[RF] Trello card - https://trello.com/c/E7gHQTc0/966-rfmainstartweatherdifferentweatherpopup-testmainstartweatherdifferentweatherpopupmenuweathericonsisclickable-timberhut
> [RF][Main][Start][Weather][DifferentWeatherPopUp] testMainStartWeatherDifferentWeatherPopUpMenuWeatherIconsIsClickable <Timberhut>

- src/test/java/IraKalinkaTest.java
- src/test/java/IriSamoTest.java
- src/test/java/TchernomorTest.java
testCheckIconsNames is added
[US] - https://trello.com/c/lAsTht1j
[TC] - https://trello.com/c/XmYs136x
[AT] - https://trello.com/c/rYHjHzmf
> [AT][Start][Weather][DifferentWeatherPopUp] testCheckIconsNames <tchernomor>

- src/test/java/IvanRamin7Test.java
Re-created and edited class instead of mine class that was deleted. 
[RF] https://trello.com/c/n75ceitk
> [RF] Homework tests instead mine deleted class <IvanRamin7>

- src/test/java/VeraFesTest.java
testImageLogo() added
[TC] - https://trello.com/c/11lfFxsb/1162-tcmainnavbarlogo-verify-the-websites-logo-exists-and-visible-verafes
[AT] - https://trello.com/c/hVzLpGFi/1163-atmainnavbarlogo-testimagelogo-verafes
> [AT][Main][NavBar][Logo] testImageLogo() added <verafes>

- src/test/java/pages/HomeMarketplacePage.java
- src/test/java/tests/HomeMarketplaceTest.java
testAllButtonsAreVisibleAndClickable() added
[POM] - https://trello.com/c/plO0r1r8/1418-pommainnavbarmenumarketplace-testallbuttonsarevisibleandclickable-vira-dmytrenko
> [POM][Main][NavBar][Menu][Marketplace] testAllButtonsAreVisibleAndClickable <vira-dmytrenko>

- src/test/java/pages/PartnersPage.java
- src/test/java/tests/PartnersTest.java
[AT] https://trello.com/c/2PjPhLUy
> [AT][Main][PartnersPage] testAreRightLinksShowed <IvanRamin7>

- src/test/java/tests/PartnersTest.java
[RF] https://trello.com/c/3t2iA1U3
> [RF][Main][PartnersPage] Changed name of testAreRightLinksShowed <IvanRamin7>
